### PR TITLE
Added SciFiTitleCard

### PR DESCRIPTION
**Pull request by azuravian**
Added new SciFiTitleCard and updated my README, the primary README and the cards.json.

### CODE REVIEW

**Comment by CollinHeist** [comment]
Okay so I made a few changes:
- I added the CardModel (required for the UI)
- Removed the specified font replacements, as those are not relevant to the default Font
- Corrected `USES_SEASON_TITLE` to `False`
- Removed all references to season text from the card (unused)
- Added the `episode_text_color` and `stroke_color` extras
- Removed the season and episode number arguments in `__init__` (unused)
- Removed the episode prefix text detection (unused)
- Added support for the interword spacing Font option
- Removed erroneous references to separate season and episode count fonts

If that all looks good, I'll test out the card and then we can merge it

**Comment by azuravian** [comment]
All sounds good to me.  I'll try to be more careful next time.  Still trying to get an understanding of all the aspects of the cardtype formatting.

**Comment by CollinHeist** [comment]
@azuravian It's not a problem, I don't have this documented anywhere and the format is very specific.

I also just added an extra to disable adding the `_` to the title text.

**Comment by azuravian** [comment]
Sounds good, I considered that myself, but it was already pretty extra heavy.  I guess more options isn't a problem though.

**Comment by CollinHeist** [comment]
Yeah you can never have enough extras! Especially since they're pretty easy to select within the UI now. But looks good! Thanks for creating this

**Pull request merged**
